# Generated by Django 2.1.5 on 2019-02-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('UK', 'UK'), ('ENGLAND', 'ENGLAND'), ('SCOTLAND', 'SCOTLAND'), ('WALES', 'WALES')], max_length=20, verbose_name=' Country Name')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 'JANUARY'), (2, 'FEBRUARY'), (3, 'MARCH'), (4, 'APRIL'), (5, 'MAY'), (6, 'JUNE'), (7, 'JULY'), (8, 'AUGUST'), (9, 'SEPTEMBER'), (10, 'OCTOBER'), (11, 'NOVEMBER'), (12, 'DECEMBER')])),
                ('tmax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tmin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('country', 'year', 'month')},
        ),
    ]
